version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3 # mantém o banco fora do container
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true

