# Generated by Django 5.2.6 on 2025-09-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_categoria_remove_cartitem_addons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='categoria',
            field=models.CharField(blank=True, default='Geral', max_length=50),
        ),
        migrations.RemoveField(
            model_name='itemdopedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='itemdopedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='addons',
            field=models.TextField(blank=True, help_text='Adicionais escolhidos, ex: Limão e Gelo', null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço do produto + adicionais', max_digits=8, null=True),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='ItemDoPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
