# Generated by Django 5.2.6 on 2025-09-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_alter_menuitem_categoria_remove_itemdopedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='categoria',
            field=models.CharField(choices=[('entradas', 'Entradas'), ('pratos_quentes', 'Pratos Quentes'), ('bebidas', 'Bebidas'), ('bebidas_alcoolicas', 'Bebidas Alcoólicas'), ('drinks', 'Drinks'), ('geral', 'Geral')], default='geral', max_length=50),
        ),
    ]
