# Generated by Django 5.2.6 on 2025-09-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_alter_menuitem_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='addons',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='final_price',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
    ]
