# Generated by Django 5.2.6 on 2025-09-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_remove_cartitem_addons_remove_cartitem_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='categoria',
            field=models.CharField(choices=[('bebida', 'Bebida'), ('comida', 'Comida'), ('sobremesa', 'Sobremesa'), ('lanche', 'Lanche'), ('outro', 'Outro')], default='comida', max_length=50),
        ),
    ]
