# Generated by Django 5.2.6 on 2025-09-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0006_alter_menuitem_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='categoria',
            field=models.CharField(choices=[('bebida', 'Bebida'), ('pratos_quentes', 'Pratos Quentes'), ('sobremesa', 'Sobremesa'), ('lanche', 'Lanche'), ('outro', 'Outro')], default='comida', max_length=50),
        ),
    ]
