# Generated by Django 5.2.6 on 2025-10-03 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_alter_menuitem_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='addons',
            field=models.TextField(blank=True, help_text='Adicionais escolhidos, ex: Limão e Gelo', null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço do produto + adicionais', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='cardapio.categoria'),
        ),
    ]
