# Generated by Django 5.2.6 on 2025-10-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0008_categoria_cartitem_addons_cartitem_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='categoria',
            field=models.CharField(choices=[('entradas', 'Entradas'), ('porcoes', 'Porções'), ('pratos_quentes', 'Pratos Quentes'), ('bebidas', 'Bebidas'), ('bebidas_alcoolicas', 'Bebidas Alcoólicas'), ('drinks', 'Drinks'), ('sobremesas', 'Sobremesas')], default='pratos_quentes', max_length=50),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
