# Generated by Django 5.2.6 on 2025-10-08 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0009_alter_menuitem_categoria_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoDeImagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Um nome descritivo para a imagem, ex: 'Foto do Hambúrguer Clássico'", max_length=100)),
                ('imagem', models.ImageField(upload_to='banco_de_imagens/')),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='imagem',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='imagem_selecionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardapio.bancodeimagens', verbose_name='Imagem do Banco'),
        ),
    ]
