# Generated by Django 5.2.7 on 2025-10-17 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0011_pedido_itempedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='addons',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações extras do cliente', null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço do produto + adicional', max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='AdicionalProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Copo com gelo, Limão espremido', max_length=100)),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=0, help_text='Valor extra (0 se for grátis)', max_digits=6)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionais', to='cardapio.menuitem')),
            ],
            options={
                'verbose_name': 'Adicional do Produto',
                'verbose_name_plural': 'Adicionais dos Produtos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='adicional_escolhido',
            field=models.ForeignKey(blank=True, help_text='Adicional selecionado pelo cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardapio.adicionalproduto'),
        ),
    ]
